"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['client.py']
DATA_FILES = []
OPTIONS = {
   "iconfile":"../../media/Icon.icns",##自定义app图标
    'plist': {
        'argv_emulation': True,
        'CFBundleName': "TripleX",
        'CFBundleDisplayName': "TripleX",
        'CFBundleGetInfoString': "局域网文件分享工具",
        'CFBundleIdentifier': "com.metachris.osx.sandwich",
        'CFBundleVersion': "2019-01-22-0.1.0",
        'CFBundleShortVersionString': "2019-01-22-0.1.0",
        'NSHumanReadableCopyright': u"版权所有 © 2019, vincent770",
        'Localization native development region':'China'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
